feat: management command to clean up roles for all users
nelc/futurex-openedx-extensions pull request #103
Opened 2024-10-18 15:31 UTC by shadinaif

feat: management command to clean up roles for all users

Dry run:
```bash
python manage.py lms course_access_roles_clean_up
```

Commit:
```bash
python manage.py lms course_access_roles_clean_up --commit=yes
```

2024-10-19 16:19 UTC, OmarIthawi requested changes
Thanks @shadinaif! Looks great!

I've added few suggestions.

2024-10-19 16:19 UTC, OmarIthawi commented on futurex_openedx_extensions/helpers/management/commands/course_access_roles_clean_up.py
> +                continue
Inactive role should lose all of its roles to avoid data accidential data breaches.

2024-10-19 16:19 UTC, OmarIthawi commented on futurex_openedx_extensions/helpers/management/commands/course_access_roles_clean_up.py
> +            if is_system_staff_user(user):
Is staff should lose all of its roles to avoid needless permissions appearing on the admin pages.

2024-10-19 16:19 UTC, OmarIthawi commented on futurex_openedx_extensions/helpers/management/commands/course_access_roles_clean_up.py
> +                org__in=all_orgs,
I think this is case-sensitive, which shouldn't be.

2024-10-19 16:19 UTC, OmarIthawi commented on futurex_openedx_extensions/helpers/management/commands/course_access_roles_clean_up.py
> +    def handle(self, *args: list, **options: Dict[str, str]) -> None:
Please move the `def handle` into a `clean_roles` util function, this would help testing and actual usage in the future by `/admin` panel actions.

2024-10-31 04:46 UTC, shadinaif commented
I'll get back to this later. Tehreem is working on adding `library` support. I'll update my code after that to make it more robust

2026-06-14 12:56 UTC, closed without merging