feat: add my-roles API
nelc/futurex-openedx-extensions pull request #93
Opened 2024-10-08 15:39 UTC by shadinaif

feat: add my-roles API

```
GET api/fx/roles/v1/my_roles/
```

It'll work and return a result as long as the user is a system-staff, or has at least one role in the tenant. The result is the same one from get-users-roles API, but for one record with no list. Example:
```json
{
    "user_id": 12,
    "email": "shadinaif+2@gmail.com",
    "username": "shadinaif",
    "full_name": "Shadi Naif",
    "alternative_full_name": "",
    "global_roles": [],
    "tenants": {
        "4": {
            "tenant_roles": [
                "data_researcher"
            ],
            "course_roles": {}
        }
    }
}
```

2024-10-08 18:07 UTC, omar-nelc submitted a review, later dismissed
@shadinaif thanks!!

**Requested change:** `is_superuser` and `is_staff` should be returned even if it's a single property `is_staff_or_superuser`. The frontend has no other way of knowing this information.

**Question:** Do you think it should accept a `tenand_ids` GET parameter to scope the API call?

2024-10-08 18:09 UTC, OmarIthawi requested changes
@shadinaif thanks!!

Requested change: is_superuser and is_staff should be returned even if it's a single property is_staff_or_superuser. The frontend has no other way of knowing this information.

Question: Do you think it should accept a tenand_ids GET parameter to scope the API call?

2024-10-16 08:07 UTC, shadinaif commented
@OmarIthawi I've added `is_staff_user` to the response

> Question: Do you think it should accept a tenand_ids GET parameter to scope the API call?
it accepts tenant ids already. All `GET` APIs in the dashboard accept the `tenant_ids` filter

2024-10-16 11:01 UTC, tehreem-sadat approved these changes
Looks good.

2024-10-16 12:00 UTC, merged